#!/bin/bash

# get port, node, user
port=$(shuf -i6006-7999 -n1)
node=$(hostname)
user=$(whoami)

# print tunneling instructions jupyter-log
echo -e "
For more info and how to connect from windows, see:
   https://docs.ycrc.yale.edu/clusters-at-yale/guides/jupyter/
   https://rabernat.github.io/research_computing/running-jupyter-notebooks-on-habanero.html
   https://confluence.columbia.edu/confluence/display/rcs/Habanero+HPC+Cluster+User+Documentation

MacOS or linux terminal command to create your ssh tunnel
ssh -N -L ${port}:${node}:${port} ${user}@habanero.rcs.columbia.edu

Windows MobaXterm info
Forwarded port:same as remote port
Remote server: ${node}
Remote port: ${port}
SSH server: ${cluster}.habanero.rcs.columbia.edu
SSH login: $user
SSH port: 22

Use a Browser on your local machine to go to:
localhost:${port}  (prefix w/ https:// if using password)
"

# run
tensorboard --logdir=./data/logs/fit  --port=$port --bind_all
